namespace AppointmentManagement.Models.Domain
{
    // Created a UserRole Datatype for Role
    public enum UserRole
    {
        Doctor, Patient
    }

    public class User
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public UserRole Role { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string? PasswordHash { get; set; } //AutoGenerated // Add this for storing hashed passwords

        // Navigation properties
        public List<Appointment>? PatientAppointments { get; set; } = [];
        public List<Appointment>? DoctorAppointments { get; set; } = [];
    }
}
